import ContextMenuManager from "@/components/context-menu/ContextMenuManager";
import ModalManager from "@/components/ModalManager";
import { ContextMenuProvider } from "@/context/ContextMenuContext";
import { ModalContextProvider } from "@/context/ModalContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const rubik = Rubik({
//   variable: "--font-rubik",
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: Readonly<React.ReactNode>;
};

export default async function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased wrapper`}>
        <ModalContextProvider>
          <ContextMenuProvider>
            <ModalManager />
            <ContextMenuManager />

            {children}
            <div id="modal" />
            <div id="context-menu" />
          </ContextMenuProvider>
        </ModalContextProvider>
      </body>
    </html>
  );
}
