import ModalManager from "@/components/ModalManager";
import Navbar from "@/components/Navbar";
import { ModalContextProvider } from "@/context/ModalContext";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const rubik = Rubik({
//   variable: "--font-rubik",
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// const inter = Inter({
//   variable: "--font-inter",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased `}>
        <ModalContextProvider>
          <ModalManager />
          <Navbar />
          {children}
          <div id="modal" />
        </ModalContextProvider>
      </body>
    </html>
  );
}
